name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we want to test our package on several versions of Python
        python-version: [3.10.6]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        # make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry flake8 pytest
          make install
      - name: Run linter 
        run: make lint
      - name: Run tests
        run: make test 
      - name: Create Reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.11.0-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter 
          ./cc-test-reporter before-build
      - name: run test-coverage
        run: make test-coverage
      - name: Sending Repo
        env:
          GITHAB_TOKEN: ${{ secrets.TEST_REPORTER_ID }}
        run:  |
         ./cc-test-reporter after-build -r $GITHAB_TOKEN
